### ISSUE TITLE
univariate  or multivariate 

### ISSUE THREAD

**Issue by zhouzexufly** [effa/time-series-clustering#1]
Excuse me, is this univariate time series clustering or multivariate time series clustering?

**Comment by effa** [comment]
Multivariate.

But it was just a "quick and dirty" exploration as a school homework, I am sure you can find plenty of much more useful resources on this topic.

**Comment by zhouzexufly** [comment]
Thank you very much. Good luck.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "effa/time-series-clustering"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月31日(星期一) 晚上7:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [effa/time-series-clustering] univariate  or multivariate  (#1)





 
Multivariate.
 
But it was just a "quick and dirty" exploration as a school homework, I am sure you can find plenty of much more useful resources on this topic.
